language: objective-c

before_install:
  - gem install xcpretty --no-rdoc --no-ri --no-document --quiet
  - gem install slather

env:
  global:
    - LC_CTYPE=en_US.UTF-8
    - LANG=en_US.UTF-8
    - PROJECT_NAME="SharedHelpers"
    - PROJECT_SUFFIX=".xcodeproj"
    - FRAMEWORK_SCHEME="SharedHelpers"
    - IOS_SDK=iphonesimulator10.0

matrix:
  include:
    # - osx_image: xcode8
    #   env: SCHEME="macOS"  SDK="macosx10.12"          DESTINATION="arch=x86_64"
    # - osx_image: xcode8
    #   env: DESTINATION="OS=9.0,name=iPhone 6S Plus"  SCHEME="$FRAMEWORK_SCHEME" SDK="$IOS_SDK"
    # - osx_image: xcode8
    #   env: DESTINATION="OS=9.1,name=iPhone 6S"       SCHEME="$FRAMEWORK_SCHEME" SDK="$IOS_SDK"
    # - osx_image: xcode8
    #   env: DESTINATION="OS=9.3,name=iPad Pro"        SCHEME="$FRAMEWORK_SCHEME" SDK="$IOS_SDK"
    - osx_image: xcode8
      env: DESTINATION="OS=10.0,name=iPhone 7 Plus"  SCHEME="$FRAMEWORK_SCHEME" SDK="$IOS_SDK"


script:
  - set -o pipefail
  - xcodebuild -version
  - xcodebuild -showsdks
  - xcodebuild
    -project "$PROJECT_NAME$PROJECT_SUFFIX"
    -scheme "$SCHEME"
    -sdk "$SDK"
    -destination "$DESTINATION"
    -configuration Debug
    GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES
    GCC_GENERATE_TEST_COVERAGE_FILES=YES
    ONLY_ACTIVE_ARCH=YES
    test
    | xcpretty -c

after_success:
  - slather
  - bash <(curl -s https://codecov.io/bash) -J "$PROJECT_NAME" -f ./test_reports/cobertura.xml
