language: objective-c

before_install:
  - gem install xcpretty --no-rdoc --no-ri --no-document --quiet

env:
  global:
    - LC_CTYPE=en_US.UTF-8
    - LANG=en_US.UTF-8
    - PROJECT_NAME="SharedHelpers"
    - FRAMEWORK_SCHEME="SharedHelpers"

matrix:
  include:
    - osx_image: xcode8
      env: SCHEME="macOS"  SDK="macosx10.12"          DESTINATION="arch=x86_64"
    - osx_image: xcode7.3
      env: SCHEME="macOS"  SDK="macosx10.11"          DESTINATION="arch=x86_64"
    - osx_image: xcode7.3
      env: SCHEME="iOS"    SDK="iphonesimulator9.3"   DESTINATION="OS=9.3,name=iPhone 6S Plus"
    - osx_image: xcode7.3
      env: SCHEME="tvOS"   SDK="appletvsimulator9.2"  DESTINATION="OS=9.2,name=Apple TV 1080p"

script:
  - set -o pipefail
  - xcodebuild -version
  - xcodebuild -showsdks
  - xcodebuild
    -project "$FRAMEWORK_NAME.xcodeproj"
    -scheme "$FRAMEWORK_NAME-$SCHEME"
    -sdk "$SDK"
    -destination "$DESTINATION"
    -configuration Debug
    ONLY_ACTIVE_ARCH=YES
    GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES
    GCC_GENERATE_TEST_COVERAGE_FILES=YES
    test
    | xcpretty -c

after_success:
  - bash <(curl -s https://codecov.io/bash) -J "$PROJECT_NAME"
